name: FischysWaypoints
version: '${project.version}'
main: me.fisch37.waypoints.FischysWaypoints
api-version: '1.19'
authors: [Fisch37]
description: An interactive waypoints system for Spigot

commands:
  waypoints:
    aliases: wps
    description: Fischys Waypoint System
    usage: /wps <add|delete|go|help|list|info|set> [<args>]
    permission: waypoints

permissions:
  waypoints:
    description: Availability of /waypoints
    default: true
  waypoints.add:
    description: Availability of /waypoints add
    default: op
  waypoints.delete:
    description: Ability to delete own waypoints
    default: true
  waypoints.delete.others:
    description: Ability to delete others' waypoints
    default: op
  waypoints.go:
    description: Ability to teleport to waypoints
    default: true
  waypoints.help:
    description: Ability to see the help page
    default: true
  waypoints.info:
    description: Ability to see information about a waypoint
    default: true
  waypoints.list:
    description: Ability to list all waypoints
    default: true
  waypoints.set:
    description: Ability to set a waypoint to a position
    default: op